### PR TITLE
Safari Splash fix

### PR DESCRIPTION
**Pull request by mwernimont**
Changes made:
-----------
Description

Safari was showing a missing image error, sort of.  Wasn't really showing an error but I could tell it was an issue based on its behavior.

It apparently didn't like us having the webp image used as two different source options.  Once I removed one of them it went back to working order.  Let me know if you see something off after this change.  

Testing:
----------------------------
Before making this pull request, I:
- [ ] Cleaned the code the way Vue likes it - run 'npm run lint --fix'        
- [x] Made sure all tests run
- [ ] Ran WAVE plugin 508 compliance tool

I can confirm this has been checked on:
- [x] Chrome
- [x] Safari
- [ ] Edge
- [x] Firefox
- [ ] Samsung Internet
- [ ] Internet Explorer 11 (not supported, but still needs at least a working user redirect page)

### CODE REVIEW

**Comment by mwernimont** [comment]
**Before:**
Screen Shot 2021-03-18 at 2 23 02 PM

**After:**
Screen Shot 2021-03-18 at 2 23 19 PM

**Comment by collnell** [comment]
A+

**Comment by collnell** [comment]
I'm seeing that some splash images are not  full screen at the largest screen size:

**Comment by mwernimont** [comment]
@collnell specifically safari?  I have full screen images on Chrome, Firefox, and Safari on my 38in monitor. What browser and size are you looking at?

Screen Shot 2021-03-22 at 12 07 26 PM

**Pull request merged**
