### PR TITLE
ridge buttons fix

### PR DESCRIPTION
**Pull request by mwernimont**
Changes made:
-----------
Description

We had all the inputs inside a h4 tag, which isn't the best HTML procedure.  So I took the inputs out, spaced out the compare box and I think it looks and works great on mobile now.

Testing:
----------------------------
Before making this pull request, I:
- [ ] Cleaned the code the way Vue likes it - run 'npm run lint --fix'        
- [x] Made sure all tests run
- [ ] Ran WAVE plugin 508 compliance tool

I can confirm this has been checked on:
- [x] Chrome
- [x] Safari
- [ ] Edge
- [x] Firefox
- [ ] Samsung Internet
- [ ] Internet Explorer 11 (not supported, but still needs at least a working user redirect page)

### CODE REVIEW

**Comment by mwernimont** [comment]
Screenshot_20210331-134604

**Comment by mwernimont** [comment]
If there was a different look on Desktop you wanted and thats why it was stacked inside the h4, let me know and I can make just about anything happen.

**Comment by collnell** [comment]
I had done that because I wanted them all to be on the same line on desktop so the chart, buttons, and the caption all fit in one view. I couldn't figure out how to get them to be on the same line without the being grouped together like that, are you able to do that?

**Comment by mwernimont** [comment]
I can make that happen.

**Comment by mwernimont** [comment]
@collnell ?

Screen Shot 2021-03-31 at 2 17 58 PM

**Comment by mwernimont** [comment]
Better spacing
Screen Shot 2021-03-31 at 2 20 58 PM

**Review by collnell — CHANGES_REQUESTED** [review]
Can we do it like this? 
image

Also let's keep the button group at the same width or less than the charts on both mobile and desktop.

**Comment by mwernimont** [comment]
Screen Shot 2021-03-31 at 3 13 55 PM

**Review by collnell — APPROVED** [review]

**Pull request merged**
